services:
  - type: web
    name: apex-ai-n8n
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: NODE_ENV
        value: "production"
      - key: WEBHOOK_URL
        value: "https://apex-ai-n8n.onrender.com"
      - key: TWILIO_ACCOUNT_SID
        fromSecret: "TWILIO_ACCOUNT_SID"
      - key: TWILIO_AUTH_TOKEN
        fromSecret: "TWILIO_AUTH_TOKEN"
      - key: REDIS_URL
        value: "redis://red-d0b9s41r0fns73d99e1g:6379"
      - key: OPENAI_API_KEY
        fromSecret: "OPENAI_API_KEY"
      - key: ELEVENLABS_API_KEY
        fromSecret: "ELEVENLABS_API_KEY"
      - key: DEEPGRAM_API_KEY
        fromSecret: "DEEPGRAM_API_KEY"
      - key: GOOGLE_CLIENT_ID
        fromSecret: "GOOGLE_CLIENT_ID"
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: "GOOGLE_CLIENT_SECRET"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_SECURE
        value: "true"
      - key: SMTP_USER
        fromSecret: "SMTP_USER"
      - key: SMTP_PASS
        fromSecret: "SMTP_PASS"

  - type: redis
    name: apex-ai-redis
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: "0.0.0.0/0"
        description: "Allow all IPs for testing"
