# Example render.yaml for n8n + Redis
services:
  - type: redis
    name: redis
    plan: starter

  - type: web
    name: n8n
    env: docker
    image: n8nio/n8n:latest
    plan: starter
    envVars:
      - key: REDIS_HOST
        fromService:
          name: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis
          property: port
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "<your‑username>"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "<your‑password>"
      - key: NODE_ENV
        value: production
    # (add ports, health checks, volumes, etc. as needed)
